version: '2'
services:
  web:
    image: markwatsonatx/swift-kitura-sample:1.7    
    volumes:
      - ./src:/usr/src
    environment:
      - KITURA_SAMPLE_HOME=/usr/src
    ports:
      - "38090:8090"
